#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

# this hook is only called once until the template directory is clone
# once the template directory is cloned the, the clone hook from the template directory
# will be run instead of this file.  This is on purpose in order to allow the user
# to easily to customize the hook.

@template_dir    = ARGV[0] || File.join(ENV['HOME'], '.retrospec', 'repos', 'retrospec-puppet-templates')
@template_repo   = ARGV[1] || 'https://github.com/nwops/retrospec-templates'
@template_branch = ARGV[2] || 'master'

def create_repo(template_dir, git_url, branch)
  # check if repo already exists
  unless git_exists?(template_dir)
    puts `git clone -b #{branch} #{git_url} #{template_dir}`
  end
end

def git_exists?(template_dir)
  File.exist? File.join(template_dir, '.git', 'config')
end

def origin_exists?(template_dir)
  `git -C #{template_dir} remote show origin`
  $CHILD_STATUS.success?
end

def update_templates(git_url, dest, branch = 'master')
  create_repo(dest, git_url, branch)
  puts `git -C #{dest} pull`
  dest
end

def connected?
  unless ENV['CLONE_RETROSPEC_TEMPLATES'].nil?
    # if the user wants internet but doesn't want cloning, allow them to set this variable
    return false
  end
  open('http://www.google.com/') rescue false
end

# sometimes I work on an airplane and don't care to clone everything all the time
# so lets check for connectivity first
update_templates(@template_repo, @template_dir, @template_branch) if connected?
